
CREATE TABLE IF NOT EXISTS properties (
id SERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL,
location VARCHAR(255) NOT NULL,
price VARCHAR(255) NOT NULL,
imageUrl VARCHAR(255) NOT NULL,
url VARCHAR(255) NOT NULL UNIQUE,
viewedOnline BOOLEAN DEFAULT false,
contactedAgent BOOLEAN DEFAULT false,
viewedProperty BOOLEAN DEFAULT false,
madeOffer BOOLEAN DEFAULT false,
createdAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);